### PR TITLE
#93 deploy script zip directory

### LINKED ISSUE #92: Build is currently broken
```
...:coda-prototype lukechurch$ tsc
src/io/FileUtils.ts(1,1): error TS6054: File '/Users/lukechurch/GitRepos/coda/coda-prototype/UIUtils.js' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.
src/io/FileUtils.ts(88,34): error TS2304: Cannot find name 'Papa'.
src/io/FileUtils.ts(119,34): error TS2304: Cannot find name 'Papa'.
src/io/FileUtils.ts(153,29): error TS2304: Cannot find name 'Papa'.
src/io/FileUtils.ts(275,29): error TS2304: Cannot find name 'Papa'.
src/io/FileUtils.ts(323,43): error TS2304: Cannot find name 'UIUtils'.
```

### LINKED ISSUE #93: Deploy Script

### PR DESCRIPTION
**Pull request by as2388**
Revised deploy script to use the file system version rather than HEAD, emitting a warning if HEAD does not match the directory version.

This closes #93 and closes #92

### CODE REVIEW

File: coda-prototype/deploy.sh [hunk 1]
```diff
@@ -1,31 +1,29 @@
...
+
+    # Write the hash and time-stamp to a file
+    echo "{\"hash\": \"$hash\", \"date\": \"$date\"}" >version.json
+fi
+
+# Delete the previously deployed version, if it exists, so that it is not included in the next zip file.
+[ -e coda.zip ] && rm coda.zip
+
+# Zip this directory into coda.zip
+zip -r -qq coda.zip .
```
Comment (lukechurch) [inline coda-prototype/deploy.sh]: Could you stick the version number on the end of the zip file? That will make it easier to upload to GitHub releases which we use to send the code see: https://github.com/lukechurch/coda/releases

**Comment by lukechurch** [comment]
Thanks for the changes :)

**Comment by as2388** [comment]
Closes #92
